### PR TITLE
Block resize array

### PR DESCRIPTION
**Pull request by AnastasiyaRagozina**
We implement common functions: fold, map, iter, filter, find, tryFind, IEnumerable interface for BlockResizeArray. 
Example of performance tests results:
* Fold function: 
   * resizeArray 178.7ms
   * array 74.8ms
   * blockResizeArray 74.6ms
* Map function: 
   * resizeArray 203.9ms
   * array 136.8ms
   * blockResizeArray 190.5ms

### CODE REVIEW

**Comment by forki** [comment]
could you please check the red build? thx

**Comment by gsvgit** [comment]
@forki, @AnastasiyaRagozina 

 Results of my investigation:
1) Local build for linux/mono and windows/.NET with build.(sh|cmd) works fine.
2) Seems that it is CI server configuration problem. I check [last builds](https://travis-ci.org/fsprojects/FSharpx.Collections/pull_requests). Builds on workers with name ``` worker-jupiter-brain:*```  all failed with message 
```
Paket failed with:
	The requested feature is not implemented.
The command "./build.sh" exited with 1.
 ```  

Last build failed with the same message. Unfortunately I don't know how to manage CI server workers, so I can not fix problem.

 FYI. [Build on worker with name ```worker-linux-docker-9114a178.prod.travis-ci.org:travis-linux-2```](https://travis-ci.org/fsprojects/FSharpx.Collections/builds/68847689) is succeeded.

**Comment by forki** [comment]
oh I know that one. It means it was run on old mono. Let me check.

**Comment by forki** [comment]
please merge d89c930 into your pull request, or rebase on current master. then we see if it is fixed.

**Comment by forki** [comment]
very cool. thx

**Pull request merged**
