### PR TITLE
Add zip to NonEmptyList

### LINKED ISSUE #40: Implement zip on NonEmptyList
The `NonEmptyList` type currently does not have a `zip` implementation. This comes in handy quite often.

### PR DESCRIPTION
**Pull request by yever**
- add test
- closes #40

### CODE REVIEW

**Comment by mausch** [comment]
Thanks @yever , however the signature for `zip` should be `NonEmptyList<'a> -> NonEmptyList<'b> -> NonEmptyList<'a * 'b>`, could you please fix that?
Also the test should operate on NonEmptyList instances, not `int array`s.

**Comment by yever** [comment]
You are welcome, @mausch.

I'm sorry about the signature. That's a flop and I can easily fix it.

The problem with the test is that it's difficult to use ``fsCheck`` to generate equal-sized collections (unless I'm missing something). My solution was to create two ``int array``s, slice from them their shared length and convert them to ``NonEmptyList``s. Then, once I have two equal-sized ``NonEmptyList``s I can test if they ``zip`` the same as ``list``s do. Would it be better to use a static test-case, like in the [FlatList test](https://github.com/fsprojects/FSharpx.Collections/blob/7fce986a195929bc2e859cea19c628518b7f683f/tests/FSharpx.Collections.Experimental.Tests/FlatListTest.fs#L398)? What would you suggest?

**Comment by mausch** [comment]
Ah, right, I forgot that `List.zip` throws when the lengths are different. So we need two tests here: one for the case where lists have the same length and another for the case where they don't.

I'd use custom generators for this e.g. you could use this to generate two NELs of the same length:

```fsharp
let twoNELs = 
    gen {
        let! a = NonEmptyListGen.NonEmptyList<int>().Generator
        let! b = Gen.listOfLength a.Length Arb.generate<int> |> Gen.map (fun a -> NonEmptyList.create a.[0] (List.tail a))
        return a,b
    }
```

What do you think?

**Comment by yever** [comment]
Looks good. I'lll have to dive into FsCheck. It's a good opportunity to learn it.

**Comment by yever** [comment]
Ok, I've corrected my pull request:
- ``zip`` returns a ``NonEmptyList``.
- The test generates ``NonEmptyList``s of equal length.
- I've added another test that makes sure that ``zip`` raises an exception when the lengths are different, but doesn't when they're equal.

**Comment by forki** [comment]
thx

**Comment by mausch** [comment]
:+1:

**Comment by yever** [comment]
Thank you :)

**Pull request merged**
