### PR TITLE
Gitpod support

### PR DESCRIPTION
**Pull request by cartermp**

### CODE REVIEW

**Comment by knocte** [comment]
@sergey-tihon I guess this can be closed because it has been superseded by https://github.com/fsprojects/FSharpx.Collections/pull/177 ?

**Comment by cartermp** [comment]
Oh hell yeah, let's do that

**Comment by sergey-tihon** [comment]
no gitpod support? 😢

**Comment by cartermp** [comment]
Oh, right, I forgot that I never pushed some of the build updates I had. Let's do this.

**Comment by sergey-tihon** [comment]
@cartermp what is missing in this PR? gitpod link from readme?

**Comment by cartermp** [comment]
Should be good when green.

**Comment by sergey-tihon** [comment]
Should we install dotnet to gitpod?

image

**Comment by cartermp** [comment]
Okay, I specified it wrong but it's correct now. There was a separate issue with a System.AggregateException thrown when the build script was invoked though. It almost looked like it was in the SDK.

**Comment by sergey-tihon** [comment]
Looks like `dotnet restore`  is not fixed yet in gitpod - https://community.gitpod.io/t/cannot-run-dotnet-tool-restore/4388

**Comment by cartermp** [comment]
@sergey-tihon this is good to go - gitpod updated their infrastructure to not be tied to the busted kernel they were on, so .NET now works again, yay!

**Comment by cartermp** [comment]
Ooof, FAKE doesn't support .NET 6.

**Comment by cartermp** [comment]
Kidding, it was this:

`"tests/**/bin/Release/net6.0/*Tests.dll"`

I really dislike this janky hardcoded shit with FAKE and expecto. So fragile when things change

**Comment by sergey-tihon** [comment]
Thank you @cartermp !

**Pull request merged**
