### PR TITLE
Fantomas5

### PR DESCRIPTION
**Pull request by sergey-tihon**
This draft is here to check with maintainers and core contributors Fantomas 5 formatting and decide merge or don't

Detected issues:
- https://github.com/fsprojects/fantomas/issues/2511
- https://github.com/fsprojects/fantomas/issues/2512
- https://github.com/fsprojects/fantomas/issues/2517
- https://github.com/fsprojects/fantomas/issues/2518

Would love to hear opinions/reactions from @forki @jackfoxy @pblasucci @eacasanovaspedre @gdziadkiewicz @sideeffffect @gsvgit

### CODE REVIEW

**Comment by pblasucci** [comment]
My mother always told me, "if you don't have anything nice to say, don't say anything at all."
😉

So I'll abstain, and leave the decisions to folks who have more skin in the game. 👍

**Comment by sideeffffect** [comment]
I've always liked automated formatting. But it's been such a long time since I've contributed to this repository that I don't feel my voice has much value :wink:

**Comment by gdziadkiewicz** [comment]
I love the idea! Can we somehow help with the initiative?

**Comment by sergey-tihon** [comment]
> I love the idea! Can we somehow help with the initiative?

I think that I do not need technical help, PR is already green. I'll wait for the next patch release for Fantomas to update it and format ignored files.

But I need help with the review of the change. Currently, I used my `.editorconfig` with some personal preferences for F# code formation. We need to check if it works for all contributors and maybe change something if it does not fil this project.

**Comment by gdziadkiewicz** [comment]
@sergey-tihon is this ready for review?

**Comment by sergey-tihon** [comment]
@gdziadkiewicz yes,  but after merging this we break all other PRs

**Comment by sergey-tihon** [comment]
@gdziadkiewicz done

**Review by gdziadkiewicz — APPROVED** [review]

**Pull request merged**
