### PR TITLE
Modernise build

### PR DESCRIPTION
**Pull request by sergey-tihon**
- [x] Drop `net45` support and release only `netstandard2.0` assemblies
- [x] Migrate to GitHub actions (remove Travis CI and AppVeyour) 
- [x] Migrate to Paket 6, build with .NET 5 and Node 14
- [x] Migrate to [fsdocs](https://fsprojects.github.io/FSharp.Formatting/upgrade.html)
- [x] Publish CI Nuget package to Github NuGet feed
- [ ] Release workflow

Optional
- [ ] Test with Fable 3 (instead of Fable 2)

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@knocte do you want to help with tests migration to Fable 3 or docs to fsdocs?

**Comment by knocte** [comment]
I was willing to help on the GithubActions migration because I'm familiar with GithubActions. I'm not familiar with Fable or fsdocs.

**Comment by knocte** [comment]
Can we leave Fable&fsdocs for another PR?

**Comment by sergey-tihon** [comment]
Fable 3 - maybe, because tests with Fable 2 runs OK.
fsdocs - i would say No, if we merge without docs we will left then our of sync for a long time

**Comment by knocte** [comment]
> fsdocs - i would say No

What's wrong with the older docs system? Why is it out of sync?

**Comment by sergey-tihon** [comment]
> What's wrong with the current docs system? 

It is old and broken (I think).

Current master depends on FSharp.Formatting v7 (but most likely build with v3) and has a lot of auto-generated files committed. Latests version of FSharp.Formatting (v11) ship as `dotnet tool` (`fsdoc`) and does not require so many customisations in repo.

**Comment by sergey-tihon** [comment]
@jackfoxy do not you mind to drop `net45` assemblies from nuggets packages and release only `netstandard2.0`  assemblies?

**Comment by jackfoxy** [comment]
> @jackfoxy do not you mind to drop `net45` assemblies from nuggets packages and release only `netstandard2.0` assemblies?

Yes, I am in favor of that.

**Pull request merged**
