### PR TITLE
Moves to SDK style project files

### PR DESCRIPTION
**Pull request by ChrSteinert**
First step for .NET Standard Support.

I left a few things I believe are not directly necessary like ProjectGuid or BindingRedirects.
Please review and advise!

### CODE REVIEW

**Comment by panesofglass** [comment]
Probably similar to #77

**Comment by jackfoxy** [comment]
@ChrSteinert  good work. I made several "improvements" locally. Including adding netstandard2.0 as a target and updating to the latest FSharp.Core.

The travis CI failing may be as simple as adding ````dotnet : 2.1.4```` to .travis.yml, but I am not experiencec with Travis.

My "enhanced" local build fails on several (but not all) experimental tests,

````Could not load file or assembly 'nunit.framework ...````

despite binding redirects that look valid.

The binding redirects are a mess, and should not be necessary in a modern SDK library project. Indeed IMO the entire app.config files should go away. The only way I know for sure to accomplish this is to migrate all the tests to Expecto. That's a bit of a chore.

Perhaps @forki  would be so kind as to create a 2.0 branch here, and we could collaborate on that branch.

**Comment by ChrSteinert** [comment]
Cool!
Is this somewhere so we could have a look and proceed from that state further?

**Comment by jackfoxy** [comment]
@ChrSteinert  see https://github.com/fsprojects/FSharpx.Collections/issues/77#issuecomment-383395949

**Comment by ChrSteinert** [comment]
Closing this as we are working on this over here: https://github.com/jackfoxy/FSharpx.Collections/tree/netstandard

**Comment by jackfoxy** [comment]
Actually the place to work on this is now here https://github.com/fsprojects/FSharpx.Collections/tree/netstandard

**Pull request closed without merging**
