### PR TITLE
Fable tests in Travis

### PR DESCRIPTION
**Pull request by njlr**
* Adds Fable tests to Fake
 * Adds Node to Travis

### CODE REVIEW

**Comment by jackfoxy** [comment]
@njlr fails in both CIs

**Comment by njlr** [comment]
Yeah I am trying to figure out what is going wrong. The problem is with the Paket install step:

```
Downloading System.AppContext 4.3 (Formatting)

  Something went wrong while downloading System.Diagnostics.Tools 4.3

  Message: Could not download System.Diagnostics.Tools 4.3 from https://www.nuget.org/api/v2/package/System.Diagnostics.Tools/4.3.0.

    ==> Trying again

  Downloading System.Diagnostics.Tools 4.3 (Formatting)

  Something went wrong while downloading System.Security.Cryptography.Cng 4.6

  Message: Could not download System.Security.Cryptography.Cng 4.6 from https://www.nuget.org/api/v2/package/System.Security.Cryptography.Cng/4.6.0.

    ==> Trying again

  Downloading System.Security.Cryptography.Cng 4.6 (Formatting)

  Source 'https://www.nuget.org/api/v2' exception: System.Exception: Could not retrieve data from 'https://www.nuget.org/api/v2/FindPackagesById()?semVerLevel=2.0.0&id='System.Reflection.Emit'' ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00026] in <b0e1ad7573a24fd5a9f2af9595e677e7>:0 
```

**Comment by njlr** [comment]
It passes now. I suggest squashing to remove the noisy commits.

**Comment by jackfoxy** [comment]
@njlr 
1) Looks like you may have also fixed https://github.com/fsprojects/FSharpx.Collections/issues/141 but need to see a few more successes. Originally this problem was sporadic. Lately it has appeared to be constant.

2) However, now the Appveyor CI fails. Please try to get this working.

3) I never had to master git rebase. I like your idea of squashing. Can you give me the idiot proof steps?

**Comment by njlr** [comment]
2. I thought Appveyor was broken anyway?

3. I think GitHub offers a "squash and merge" option on pull requests

**Comment by jackfoxy** [comment]
I really don't understand the Travis build. Looks like 2 get kicked off, and in this case one of them timed out because it was not getting a response from a long-running test.

All in all I consider this a success. Thanks.

**Pull request merged**
