### PR TITLE
Implement ofSeq, ofList and ofArray for NonEmptyList

### PR DESCRIPTION
**Pull request by yever**
- Add tests

### CODE REVIEW

**Comment by yever** [comment]
Hello @forki & @mausch.
Is there anything wrong with this pull request?

**Comment by forki** [comment]
Probably not. But I don't monitor this very closely. Actually I think we
need another maintainer for this project.

**Comment by yever** [comment]
Well, I'd be happy to help if that's what you mean.

**Comment by mausch** [comment]
Sorry, I was on vacation until yesterday. PR looks good to me.
I agree about having more maintainers, I think @yever is a good fit :)

**Comment by mausch** [comment]
BTW I can't seem to merge this, @forki could you give me write access? Thanks.

**Comment by forki** [comment]
done. Regarding releases: I need your nuget names.

**Comment by mausch** [comment]
Thanks @forki , my nuget username is "mausch"

**Comment by forki** [comment]
done. release process is described in http://fsprojects.github.io/ProjectScaffold/release-process.html

let me know if you have problems

**Pull request merged**
