### PR TITLE
Update paket.template

### PR DESCRIPTION
**Pull request by njlr**
* Pack source-files for Fable

### CODE REVIEW

**Comment by njlr** [comment]
Please can someone take a look at this one?

https://github.com/fsprojects/FSharpx.Collections/issues/185

**Comment by njlr** [comment]
Sorry to bump!

**Comment by gdziadkiewicz** [comment]
Hi, did you confirm that the content of the nuget package created after this change is as expected?

**Comment by njlr** [comment]
> Hi, did you confirm that the content of the nuget package created after this change is as expected?

Yes can confirm. There is a `fable` folder with the source-code inside.

**Comment by gdziadkiewicz** [comment]
Relased in 3.1.0 https://www.nuget.org/packages/FSharpx.Collections/3.1.0

**Pull request merged**
